development:
  secret_key_base: ec34b6fda7f1fe36ef48fa6efbb2220f03ae9d39a96dede6ee9c91f9f54ae74a3d32ef94c7e541b327ebd02c25ed13a2aa95666830960f8a3baaee11c889b832
  TWITTER_CONSUMER_KEY: 'Voe46Sn0aFqG7CtFhSKhOfCE5'
  TWITTER_CONSUMER_SECRET: 'qUP58BuDp2tDmubeIHfQ1ruzoPcPRyhnHkoMvJXce4tMHP0syd'
  TWITTER_ACCESS_TOKEN: '3423398052-wqzqLdkZWJ6TxzkK4BdYvP7yzrjxgiLkkkhMa2K'
  TWITTER_ACCESS_TOKEN_SECRET: 'BFcCCOPgIu3948cftjISLuS2ZSHu0CbIZGo2Ew7xIm2h8'
  SPOTIFY_CLIENT_ID: 'bbed1e46557a462b830360e790ed6ef2'
  SPOTIFY_CLIENT_SECRET: 'bdc62ff9a5e344eb9a2260792697d126'

test:
  secret_key_base: 57cbd8851eb73cf41ad02ce4b327ceee93b21c75eed45b00d45fd9b86d50eb56d982d7093d20c62f2878181f87b9478d9f695102d327999842781a77495758e5
  TWITTER_CONSUMER_KEY: 'Voe46Sn0aFqG7CtFhSKhOfCE5'
  TWITTER_CONSUMER_SECRET: 'qUP58BuDp2tDmubeIHfQ1ruzoPcPRyhnHkoMvJXce4tMHP0syd'
  TWITTER_ACCESS_TOKEN: '3423398052-wqzqLdkZWJ6TxzkK4BdYvP7yzrjxgiLkkkhMa2K'
  TWITTER_ACCESS_TOKEN_SECRET: 'BFcCCOPgIu3948cftjISLuS2ZSHu0CbIZGo2Ew7xIm2h8'
  SPOTIFY_CLIENT_ID: 'bbed1e46557a462b830360e790ed6ef2'
  SPOTIFY_CLIENT_SECRET: 'bdc62ff9a5e344eb9a2260792697d126'


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  TWITTER_CONSUMER_KEY: 'Voe46Sn0aFqG7CtFhSKhOfCE5'
  TWITTER_CONSUMER_SECRET: 'qUP58BuDp2tDmubeIHfQ1ruzoPcPRyhnHkoMvJXce4tMHP0syd'
  TWITTER_ACCESS_TOKEN: '3423398052-wqzqLdkZWJ6TxzkK4BdYvP7yzrjxgiLkkkhMa2K'
  TWITTER_ACCESS_TOKEN_SECRET: 'BFcCCOPgIu3948cftjISLuS2ZSHu0CbIZGo2Ew7xIm2h8'
  SPOTIFY_CLIENT_ID: 'bbed1e46557a462b830360e790ed6ef2'
  SPOTIFY_CLIENT_SECRET: 'bdc62ff9a5e344eb9a2260792697d126'



